spring.application.name=JDBCDEMO
spring.datasource.url=jdbc:postgresql://localhost:8443/telusko
spring.datasource.username=postgres
spring.datasource.password=abgreat123
spring.datasource.driver-class-name=org.postgresql.Driver